stages:
  - build
  - release

# Runs when any tag is pushed
docker-build:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  script:
    - echo "Building Docker image with tag $CI_COMMIT_REF_NAME"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  rules:
    - if: $CI_COMMIT_TAG
  only:
    - tags

# Runs when a release is created
release:
  stage: release
  image: docker:24.0.2
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "Building and pushing Docker image for release $CI_COMMIT_TAG"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "release"
