version: "3"
services:
  app:
    image: registry.gitlab.com/parnavh/koala
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=${REDIS_URL}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    restart: always
    volumes:
      - ./tmp:/app/tmp

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --log-level warn
