version: "3"
services:
  app:
    image: registry.gitlab.com/parnavh/koala
    env_file:
      - .env
    restart: always
    volumes:
      - ./tmp:/app/tmp
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
